onboardingNET/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace onboardingNET.Models
{
    public class Task
    {
        public string Id { get; set; }
        public string TaskName { get; set; }
        public bool? Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? FinishDate { get; set; }
        public string AssignToId { get; set; }

        [ForeignKey("AssignToId")]
        public virtual ApplicationUser User { get; set; }
        public string CreatedBy { get; set; }
    }
}

onboardingNET/Models/TaskForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace onboardingNET.Models
{
    public class TaskForm
    {
        [Required]
        [Display(Name = "Task Name")]
        public string TaskName { get; set; }
        [Display(Name = "Status Name")]
        public bool? Status { get; set; }
        [Required]
        [Display(Name = "Finish Date")]
        public DateTime? FinishDate { get; set; }
        public string CreatedBy { get; set; }
        [Required]
        [Display(Name = "Assign To")]
        public string selectedValue { get; set; }
        public ApplicationUser AssignTo { get; set; }
    }
}

onboardingNET/Models/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace onboardingNET.Models
{
    public class TaskViewModel
    {
        public TaskForm Form { set; get; }
        public List<SelectListItem> ListUser { set; get; }
        public DateTime? CreatedDate { get; set; }
        public string TaskId { set; get; }
    }
}

onboardingNET/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using onboardingNET.Models;
namespace onboardingNET.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        private TaskServices _services;

        public TasksController(ApplicationUserManager userManager, TaskServices services)
        {
            this._userManager = userManager;
            _services = services;
        }
        public TasksController()
        {
            _services = new TaskServices();
        }
        public ApplicationUserManager UserManager { get; private set; }

        // GET: Tasks
        public ActionResult Index()
        {

            return View(_services.ListTask);
        }

        // GET: Tasks/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            var models=_services.ListTaskVModel();
            ViewBag.Users = models.ListUser;
            return View(_services.ListTaskVModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAsync(TaskForm form)
        {
            var fom = form;
            if (ModelState.IsValid)
            {
                var uid = User.Identity.GetUserId();
                _services.CreateTaskAsync(form.TaskName, form.FinishDate, form.selectedValue);
                return RedirectToAction("Index");
            }

            return View(form);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var models = _services.ListTaskVModelEdit(id);
            ViewBag.Users = models.ListUser;
            var task=_services.ListTaskEdit(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(models);

            //return View(task);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TaskViewModel taskView)
        {
            var form = taskView;
            if (ModelState.IsValid)
            {
                _services.EditTask(taskView);
                return RedirectToAction("Index");
            }
            return View(taskView);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var task = _services.ListTaskEdit(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            _services.DeleteTask(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

onboardingNET/Views/Tasks/Create.cshtml
@model onboardingNET.Models.TaskViewModel

@{
    ViewBag.Title = "Create";
    var Users = ViewBag.Users as IEnumerable<SelectListItem>;
}

<h2>Create</h2>


@using (Html.BeginForm("CreateAsync", "Tasks", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Task</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Form.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Form.TaskName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Form.TaskName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Form.selectedValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Form.selectedValue, @Users, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Form.selectedValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Form.FinishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Form.FinishDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Form.FinishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            $('.datepicker').datetimepicker();
        });
    </script>
}

onboardingNET/Views/Tasks/Delete.cshtml
@model onboardingNET.Models.Task

@{
    ViewBag.Title = "Delete";
}

<center><h2>Delete</h2></center>
<br />
<center><h3>Are you sure you want to delete this?</h3></center>
<div style="width: 100%;">
    <hr />
    <div style="width: 50%;margin: auto;padding: 10px;">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TaskName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TaskName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FinishDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FinishDate)
            </dd>

        </dl>
    </div>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="width: 100%;">
            <div style="width: 50%;margin-right: 50%;padding: 10px;margin-left: 40%;">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index", "Tasks", new { @class = "btn btn-primary" })
            </div>
        </div>
    }
</div>

onboardingNET/Views/Tasks/Details.cshtml
@model onboardingNET.Models.Task

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Task</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

onboardingNET/Views/Tasks/Edit.cshtml
@model onboardingNET.Models.TaskViewModel

@{
    ViewBag.Title = "Edit";
    var Users = ViewBag.Users as IEnumerable<SelectListItem>;
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Task</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TaskId)
    @Html.HiddenFor(model => model.Form.CreatedBy)
    @Html.HiddenFor(model => model.CreatedDate)

    <div class="form-group">
        @Html.LabelFor(model => model.Form.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Form.TaskName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Form.TaskName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Form.selectedValue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Form.selectedValue, @Users, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Form.selectedValue, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Form.FinishDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Form.FinishDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.Form.FinishDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Form.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Form.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Form.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@*<script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
           $('.datepicker').datetimepicker();
        });
    </script>
}

onboardingNET/Views/Tasks/Index.cshtml
@model IEnumerable<onboardingNET.Models.Task>

@{
    ViewBag.Title = "Manage Task";
}

<center><h2>Task Management</h2></center>
<br />
<a class="btn btn-success" style="float:right" href="Tasks/Create">Add Task</a>
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TaskName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignToId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinishDate)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TaskName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.FirstName) @Html.DisplayFor(modelItem => item.User.LastName)
                @*  @Html.DisplayFor(modelItem => item.User.FirstName + ' ' + item.User.LastName)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Tasks", new { id = item.Id }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Delete", "Delete", "Tasks", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>